fragment PageParts on Page {
  title
  seo {
    __typename
    title
    description
  }
  blocks {
    __typename
    ... on PageBlocksHero {
      headline
      text
      image {
        __typename
        src
        alt
        width
        height
      }
    }
    ... on PageBlocksImage {
      src
      alt
      width
      height
    }
  }
}

fragment PostsParts on Posts {
  title
  body
}
