fragment PageParts on Page {
  title
  path
  seo {
    __typename
    title
    description
  }
  blocks {
    __typename
    ... on PageBlocksHero {
      headline
      text
    }
  }
}

fragment PostsParts on Posts {
  title
  body
}
